name: Development_Workflow
on: 
  push:
  pull_request:
  workflow_call:

jobs:
    linting:
      runs-on: windows-latest
      steps:
          - name: Checkout Repo
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
          
          - name: Setup Environment
            uses: ./.github/workflows/setup_code

          - name: Install project
            run: uv sync

          - name: Linting
            run: uv run ruff format --check --diff

    testing:
      needs: linting
      runs-on: windows-latest

      steps:
          - name: Checkout Repo
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
          
          - name: Setup Environment
            uses: ./.github/workflows/setup_code

          - name: Install project
            run: uv sync

          - name: Testing
            run: uv run pytest --disable-warnings -q

    type_check:
        runs-on: windows-latest
        needs: linting

        steps:
            - name: Checkout Repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

            - name: Setup Environment
              uses: ./.github/workflows/setup_code

            - name: Install project
              run: uv sync
            
            - name: Lint
              run: uv run mypy pfts

    security_check:
        needs: linting
        runs-on: windows-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
            
            - name: Setup Environment
              uses: ./.github/workflows/setup_code

            - name: Install project
              run: uv sync

            - name: Security call
              run: uv run bandit -c "pyproject.toml" -r pfts          

    gitleaks:
      runs-on: ubuntu-latest
      needs: [testing, type_check, security_check]
      steps:
          - name: Checkout Repo
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
            with:
              fetch-depth: 0  # Fetch all history for all tags and branches

          - name: Secret Searcher
            uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7  # v2.3.9
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              GITLEAKS_NOTIFY_USER_LIST: "@TrintenP"
